name: Build App

on:
    push:
        branches:
        - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: build-push
          uses: docker/build-push-action@v1
          with:
            username: ${{ secrets.DOCKER_mathilde1 }}
            password: ${{ secrets.DOCKER_Docker!2023 }}
            registry: docker.io
            repository: <your-dockerhub-username>/cd
            tag_with_sha: true
